### PR TITLE
First pull jenkins

### PR DESCRIPTION
**Pull request by arvinwiyono**

### CODE REVIEW

**Comment by dueckes** [comment]
Regarding the changes to BuildEval::Http, I'd prefer we didn't force the use of OpenSSL::SSL::VERIFY_NONE.

See responses here for reasoning:
http://stackoverflow.com/questions/5711190/how-to-get-rid-of-opensslsslsslerror

How about we provide this as a configuration option?  I'm thinking per server for maximum security.

**Comment by dueckes** [comment]
Perhaps we should extract a cc.xml parser as this format is prominent used / well known.
Happy for this to be done outside of this patch.

**Comment by dueckes** [comment]
Please remove run.rb - this is not appropriate for the public gem!

**Comment by dueckes** [comment]
build_and_install.sh is also unnecessary in the gem.

**Comment by arvinwiyono** [comment]
alright matthew. I will try to remove those two files

**Comment by arvinwiyono** [comment]
I need your help for the https and cc.xml parse

**Comment by dueckes** [comment]
Do you have any preference on our API for configuring https settings?

As an example, I was thinking:
```ruby
BuildEval.server(
    type:     :              TeamCity,
    uri:                       "https://some.teamcity.server",
    ssl_verify_mode: :none,
    username:           "guest",
    password:           "guest"
  )
```

**Comment by arvinwiyono** [comment]
That looks good for me!

**Comment by dueckes** [comment]
Hi Arvin,

I've now merged these changes into master, note that:
* I've excluded configuring the SSL verification mode for now
* I've created a CruiseControlResponse that is used within those servers supporting the CC results format

I'll create an issue to track configuring the SSL verification mode - it has highest priority!

**Pull request closed without merging**
